name: dns test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-latest', 'ubuntu-latest']
        try: ['0', '1', '2']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install
        run: |
          pip install -r requirements.txt

      - name: hostname
        run: |
          for opt in '-A' '-d' '-f'; do
              echo "hostname $opt: $(hostname $opt 2>/dev/null || echo 'error')"
          done

      - name: nslookup
        shell: bash
        run: |
          for host in "$(hostname)" "$(hostname -f)"; do
              echo 'nslookup $host: $(nslookup "host" | sed -n "s/Name:\s*\(.*\)/\1/p")'
          done

      - name: python.socket
        shell: python
        run: |
          import socket
          for expr in (
              'socket.gethostname()',
              'socket.getfqdn()',
              'socket.getfqdn(socket.gethostname())',
              'socket.getfqdn(socket.getfqdn())',
              'socket.gethostbyname_ex(socket.gethostname())[0]',
              'socket.gethostbyname_ex(socket.getfqdn())[0]'
          ):
              try:
                  result = eval(expr)
              except Exception as exc:
                  result = str(exc)
              print(f'{expr:50}: {result}')

      - name: TCP Connection Test
        run: |
          python dns_test.py
